Merged share/CoreBase/masterfiles and share/NovaBase/masterfiles to share/masterfiles
cfengine/buildscripts pull request #1021
Opened 2022-04-22 18:24 UTC by nickanderson

There is no difference in the base policy between CFEngine Community and CFEngine Enterprise. It makes sense that they not have different directories when packaged. The current difference only serves to confuse documentation.

2022-04-22 18:43 UTC, nickanderson commented
@cf-bottom give me a fast build with no tests please

2022-04-23 05:57 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=7847)](https://ci.cfengine.com//job/pr-pipeline/7847/)

 [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7847/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7847/

2022-04-25 07:49 UTC, vpodzime requested changes
Looks good to me, but seems to be breaking bootstrap.

2022-04-26 14:13 UTC, nickanderson commented
@cf-bottom give me a fast build with no tests please

2022-09-14 10:08 UTC, Lex-2008 approved these changes

2024-02-08 21:47 UTC, closed without merging