ENT-9665: Added correct permissions for build directory in Mission Portal
cfengine/buildscripts pull request #1179
Opened 2022-12-19 21:08 UTC by craigcomstock

Ticket: ENT-9665
Changelog: none

2022-12-19 21:23 UTC, nickanderson approved these changes

2022-12-20 08:28 UTC, aleksandrychev requested changes
there is a failure during the installation
```
+ mkdir -p /opt/cfengine/notification_scripts
+ chmod -R 700 /opt/cfengine/notification_scripts
+ chown -R cfapache:cfapache /opt/cfengine
+ chown -R root:cfapache /opt/cfengine/build
chown: cannot access '/opt/cfengine/build': No such file or directory
```

2022-12-20 13:46 UTC, craigcomstock commented
> there is a failure during the installation
> 
> ```
> + mkdir -p /opt/cfengine/notification_scripts
> + chmod -R 700 /opt/cfengine/notification_scripts
> + chown -R cfapache:cfapache /opt/cfengine
> + chown -R root:cfapache /opt/cfengine/build
> chown: cannot access '/opt/cfengine/build': No such file or directory
> ```

Yeah, didn't quite have time yet to test. Will adjust. :+1:

2022-12-20 13:53 UTC, aleksandrychev commented
@craigcomstock 

>Yeah, didn't quite have time yet to test. Will adjust. 👍

I pushed commit https://github.com/cfengine/buildscripts/pull/1179/commits/0a63d98c81120b1efc8587d8ae1d1c6fc2d6965a to this PR, you can force push your if this one is not good

2022-12-20 14:18 UTC, aleksandrychev approved these changes

2022-12-20 14:20 UTC, merged