Make gzip a weak dependency
cfengine/buildscripts pull request #1192
Opened 2023-01-18 17:04 UTC by Lex-2008

Investigation shows that the only place where it's _required_ was when compressing man pages. But `man` can also work with uncompressed pages.

Other places which use gzip are Federated Reporting, watchdog script, and self-upgrade on Solaris, - all these parts are not "essential".

So it was decided to downgrade gzip requirement to "Recommends".

Also worth noting that it's essential part of system on many distibutions, and it's pretty hard to find a platform without gzip.

Ticket: ENT-9113

2023-01-18 19:05 UTC, nickanderson submitted a review, later dismissed
Makes sense, tho I suggested a potential improvement for failed man page (I guess I dunno if the format I suggested would actually work.

2023-01-18 19:05 UTC, nickanderson commented on packaging/common/cfengine-hub/postinstall.sh
> +  $PREFIX/bin/$i -M > /usr/share/man/man8/$i.8 && gzip /usr/share/man/man8/$i.8 || true
Humm, what about || echo "Install gzip and run `$i -M > /usr/share/man/man8/$i.8`

2023-01-19 08:41 UTC, Lex-2008 commented on packaging/common/cfengine-hub/postinstall.sh
> +  $PREFIX/bin/$i -M > /usr/share/man/man8/$i.8 && gzip /usr/share/man/man8/$i.8 || true
I don't think it's necessary. On the only platform I've found recently to not contain `gzip`, `man` was accepting uncompressed pages no problem (although other man pages were shipped compressed, inside package) (also worth noting that `man` wasn't installed by default - I had to install it myself).

2023-01-19 14:56 UTC, craigcomstock requested changes

2023-01-19 14:56 UTC, craigcomstock commented on packaging/common/cfengine-hub/postinstall.sh
> +  $PREFIX/bin/$i -M > /usr/share/man/man8/$i.8 && gzip /usr/share/man/man8/$i.8 || true
You could split this up and check that gzip is available.
```suggestion
  $PREFIX/bin/$i -M > /usr/share/man/man8/$i.8
  command -v gzip 2>/dev/null && gzip /usr/share/man/man8/$i.8
```

Might make a bit more sense pipeline wise. I know shellcheck doesn't like you using `&& ||` due to slightly undefined/imprecise behavior like if `$PREFIX/bin/$i` fails then `true` is still called which isn't really what we want right?

2023-01-19 14:56 UTC, craigcomstock commented on packaging/common/cfengine-non-hub/postinstall.sh
> +      $PREFIX/bin/$i -M > /usr/share/man/man8/$i.8 && gzip /usr/share/man/man8/$i.8 || true
ditto above comment, I think separating this and checking for `gzip` would be better.

2023-01-23 08:35 UTC, Lex-2008 commented on packaging/common/cfengine-hub/postinstall.sh
> +  $PREFIX/bin/$i -M > /usr/share/man/man8/$i.8 && gzip /usr/share/man/man8/$i.8 || true
> if `$PREFIX/bin/$i` fails then `true` is still called which isn't really what we want right?

Hmm, old code was calling `gzip` only if `$PREFIX/bin/$i -M` succeeded. Maybe we want to preserve this behaviour, too?

2023-01-23 15:01 UTC, craigcomstock requested changes

2023-01-23 15:01 UTC, craigcomstock commented on packaging/common/cfengine-hub/postinstall.sh
> +    cf_console echo "SystemD seems to be installed, but not working."
```suggestion
    cf_console echo "systemd seems to be installed, but not working."
```

2023-01-23 15:01 UTC, craigcomstock commented on packaging/common/cfengine-hub/postinstall.sh
> +    cf_console echo "Please fix SystemD or use other ways to start CFEngine."
```suggestion
    cf_console echo "Please fix systemd or use other ways to start CFEngine."
```

2023-01-23 15:01 UTC, craigcomstock commented on packaging/common/cfengine-non-hub/postinstall.sh
> +    cf_console echo "SystemD seems to be installed, but not working."
```suggestion
    cf_console echo "systemd seems to be installed, but not working."
```

2023-01-23 15:01 UTC, craigcomstock commented on packaging/common/cfengine-non-hub/postinstall.sh
> +    cf_console echo "Please fix SystemD or use other ways to start CFEngine."
```suggestion
    cf_console echo "Please fix systemd or use other ways to start CFEngine."
```

2023-01-23 16:10 UTC, craigcomstock approved these changes

2023-01-23 16:11 UTC, merged