ENT-11901: Removed /etc/init.d/cfengine3 from EL9+ packages
cfengine/buildscripts pull request #1470
Opened 2024-06-25 16:03 UTC by nickanderson

We started getting reports of issues related to an upstream bug in
chkconfig, (it failed to install if /etc/init.d had been created already). While
not our issue, it highlighted that it's probably time to remove the old init
script from modern packages.

Ticket: ENT-11901

2024-06-26 07:30 UTC, vpodzime requested changes
Installed but unpackaged files result in errors. We need to either not install these files on EL9+ or to `rm -rf` them here in the `%install` section.

2024-06-26 07:30 UTC, vpodzime commented on packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
>  %attr(644,root,root) /etc/sysconfig/cfengine3
We don't need any of the above. (and the same applies to community and non-hub)

2024-06-26 19:19 UTC, nickanderson commented on packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
>  %attr(644,root,root) /etc/sysconfig/cfengine3
by any of the above, you mean /etc/sysconfig/cfengine3 and /etc/init.d/cfengine3 or you mean any of my changes.

2024-06-26 19:29 UTC, nickanderson commented
Made changes, is this what you meant?

2024-06-27 10:15 UTC, vpodzime commented on packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
>  %attr(644,root,root) /etc/sysconfig/cfengine3
Any of the files :grin:

2024-06-27 10:16 UTC, vpodzime commented
> Made changes, is this what you meant?

Yes! We just need to `rm` those files in the community builds as well.

2024-06-27 10:18 UTC, vpodzime commented
Let's see what jenkins thinks now: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10981)](https://ci.cfengine.com/job/pr-pipeline/)

2024-06-27 11:11 UTC, vpodzime commented
> Let's see what jenkins thinks now: [![Build Status](https://camo.githubusercontent.com/114a150bdec59814e1e01b26b00109574eefb78b8a3b12d8005b679319fc290a/68747470733a2f2f63692e6366656e67696e652e636f6d2f6275696c645374617475732f69636f6e3f6a6f623d70722d706970656c696e65266275696c643d3130393831)](https://ci.cfengine.com/job/pr-pipeline/)

```12:21:10 + rm /etc/sysconfig/cfengine3
12:21:10 rm: cannot remove '/etc/sysconfig/cfengine3': No such file or directory```
`-f` needed :)

2024-06-27 18:34 UTC, nickanderson commented
@cf-bottom jenkins, please.

2024-06-27 18:39 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=10985)](https://ci.cfengine.com//job/pr-pipeline/10985/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10985/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10985/

2024-06-28 08:03 UTC, vpodzime commented
A more focused jenkins run: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10992)](https://ci.cfengine.com/job/pr-pipeline/)

2024-06-28 08:51 UTC, vpodzime commented
> A better targeted jenkins run: [![Build Status](https://camo.githubusercontent.com/101ee09e05f368d0234b58533aa8a6048e58fb6e83825cc843fe08b5828db268/68747470733a2f2f63692e6366656e67696e652e636f6d2f6275696c645374617475732f69636f6e3f6a6f623d70722d706970656c696e65266275696c643d3130393932)](https://ci.cfengine.com/job/pr-pipeline/10992/)

```
10:30:03 Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_9/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.003f41009-33938.el9.x86_64
10:30:04 error: Installed (but unpackaged) file(s) found:
10:30:04    /etc/init.d/cfengine3
10:30:04    /etc/profile.d/cfengine.sh
10:30:04    /etc/sysconfig/cfengine3
```
Some `rm -f` still missing.

2024-06-28 08:54 UTC, vpodzime reviewed
We should not try to remove files from the build machine itself :wink:

2024-06-28 08:54 UTC, vpodzime commented on packaging/cfengine-community/cfengine-community.spec.in
> +rm -f /etc/sysconfig/cfengine3
All these should be prefixed with `$RPM_BUILD_ROOT`. And this actually applies to some older/existing places in these files.

2024-06-28 14:07 UTC, nickanderson commented on packaging/cfengine-community/cfengine-community.spec.in
> +rm -f /etc/sysconfig/cfengine3
![Uploading not-worthy.gif…]()

2024-06-28 14:34 UTC, nickanderson commented
:(

```
09:33:31 error: File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/init.d/cfengine3
09:33:31 error: File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/profile.d/cfengine.sh
09:33:31 error: File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/sysconfig/cfengine3
09:33:31 
09:33:31 
09:33:31 RPM build errors:
09:33:31     File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/init.d/cfengine3
09:33:31     File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/profile.d/cfengine.sh
09:33:31     File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/sysconfig/cfengine3
```

2024-06-28 14:43 UTC, nickanderson commented
> :(
> 
> ```
> 09:33:31 error: File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/init.d/cfengine3
> 09:33:31 error: File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/profile.d/cfengine.sh
> 09:33:31 error: File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/sysconfig/cfengine3
> 09:33:31 
> 09:33:31 
> 09:33:31 RPM build errors:
> 09:33:31     File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/init.d/cfengine3
> 09:33:31     File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/profile.d/cfengine.sh
> 09:33:31     File not found: /home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_redhat_7/cfengine-nova-hub/BUILDROOT/cfengine-nova-hub-3.24.0a.eb2dc663a-33957.el7.x86_64/etc/sysconfig/cfengine3
> ```

I don't understand why that is triggering on el7.

They are all inside of `%if %{?rhel}%{!?rhel:0} >= 9`

2024-06-28 14:44 UTC, nickanderson commented
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11002)](https://ci.cfengine.com/job/pr-pipeline/11002/)

2024-06-28 14:53 UTC, nickanderson commented
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11003)](https://ci.cfengine.com/job/pr-pipeline/11003/)

2024-07-01 12:11 UTC, vpodzime commented
> @vpodzime
> ci/bootstrap-tests — Tests finished: failure
> [Details](https://ci.cfengine.com/job/bootstrap-tests/7953/)
> @vpodzime
> ci/sequential-tests — Tests finished: failure
> [Details](https://ci.cfengine.com/job/sequential-tests/7424/)

Failures due to CentOS 7 repos being down and we need to use `vault` instead. Tested package installation and contents manually on a local CentOS 7 VM.

2024-07-01 12:11 UTC, vpodzime approved these changes
ACK

2024-07-01 12:11 UTC, merged

2024-07-01 12:47 UTC, vpodzime commented
> Failures due to CentOS 7 repos being down and we need to use `vault` instead.

https://github.com/cfengine/system-testing/pull/563

2024-07-15 20:17 UTC, nickanderson commented
Removed cherry-pick label. Vratislav thinks best to not do this in a patch release. We'll wait for customer to beg for it.

2024-11-18 17:45 UTC, craigcomstock commented
already merged to 3.24.x, cherry pick to 3.21.x: https://github.com/cfengine/buildscripts/pull/1540