ENT-11495: added step to build react components
cfengine/buildscripts pull request #1492
Opened 2024-09-04 08:39 UTC by mineralsfree

Ticket: ENT-11495
Changelog: None

2024-09-04 08:51 UTC, mineralsfree commented
[![Build Status](https://ci.cfengine.com/view/all/job/pr-pipeline/11169/badge/icon)](https://ci.cfengine.com/view/all/job/pr-pipeline/11169/)

2024-09-05 08:35 UTC, aleksandrychev requested changes
lgtm, you also need to do this here ci/setup-projects.sh

2024-09-06 10:25 UTC, aleksandrychev approved these changes

2024-09-06 14:00 UTC, craigcomstock approved these changes

2024-10-18 14:00 UTC, merged