ENT-12140: Update dependency tables
cfengine/buildscripts pull request #1497
Opened 2024-09-17 15:35 UTC by craigcomstock

2024-09-17 15:38 UTC, cf-bottom requested changes
Please use a company e-mail instead of c***@unreasonablefarm.org

2024-09-18 11:51 UTC, olehermanse commented on README.md
> +| [libxml2](http://xmlsoft.org/sources/)                                           | 2.13.3 | 2.13.1 | 2.13.1 |                          |
Curious to see 3.21.x on newer version than master and 3.24.x, but I see there was a PR merged for 3.21, and still pending for other branches, so probably makes sense.

2024-09-18 11:51 UTC, olehermanse approved these changes
Thanks for working on this :)

2024-09-18 11:51 UTC, merged

2024-09-18 14:12 UTC, craigcomstock commented on README.md
> +| [libxml2](http://xmlsoft.org/sources/)                                           | 2.13.3 | 2.13.1 | 2.13.1 |                          |
Correct. It is a bit odd but the master and 3.24.x deps updates are works in progress as 3.21 was the immediate need. Thanks!