ENT-6373 Added diffutils as vendored dependency
cfengine/buildscripts pull request #780
Opened 2020-10-12 21:44 UTC by craigcomstock

Ticket: ENT-6373
Changelog: title

2020-10-12 21:47 UTC, craigcomstock commented
@cf-bottom why not, let's try this: jenkins with exotics

2020-10-12 21:48 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5767)](https://ci.cfengine.com//job/pr-pipeline/5767/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5767/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5767/

2020-10-13 09:29 UTC, Lex-2008 commented
that's awesome, but I think that to make buildscripts actually build it, you need to add it to the `build-scripts/compile-options` file (`var_append DEPS diff`), like here: https://github.com/cfengine/buildscripts/blob/master/build-scripts/compile-options#L104

2020-10-13 14:52 UTC, craigcomstock commented
> that's awesome, but I think that to make buildscripts actually build it, you need to add it to the `build-scripts/compile-options` file (`var_append DEPS diffutils`), like here: https://github.com/cfengine/buildscripts/blob/master/build-scripts/compile-options#L104

right. I was doing `install-dependencies diffutils` yesterday. Thanks! :+1:

2020-10-13 17:14 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5778)](https://ci.cfengine.com//job/pr-pipeline/5778/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5778/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5778/

2020-10-14 15:38 UTC, craigcomstock commented
@cf-bottom jenkins with exotics please, thanks.

2020-10-14 15:39 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5782)](https://ci.cfengine.com//job/pr-pipeline/5782/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5782/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5782/

2020-10-14 19:39 UTC, craigcomstock commented
Looks like I've got mingw builds working now. Will retry with exotics.

2020-10-14 21:00 UTC, craigcomstock commented
:pizza: :tada: diff works on windows and centos6 so far. :)

2020-10-14 21:42 UTC, craigcomstock commented
As I suspected, solaris and aix (so far) don't immediately support xz compression that the source tarball is provided with.

2020-10-16 20:53 UTC, craigcomstock commented
Retry solaris and aix71 after installing xz and tar(gtar on solaris) via a prototype policy for infra: https://github.com/mendersoftware/infra/pull/180/files

[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=5798)](https://ci.cfengine.com/job/pr-pipeline/5798/)

2020-10-19 14:55 UTC, craigcomstock commented
retry exotics after core C fix

[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=5807)](https://ci.cfengine.com/job/pr-pipeline/5807/)

2020-10-20 14:05 UTC, craigcomstock commented on deps-packaging/diffutils/cfbuild-diffutils.spec
> +echo $PATH
on aix 53 the version of tar in /opt/freeware/bin isn't even new enough to understand how to use `xz` so likely we will need to "repackage" the tar.xz source package as tar.gz and let the script made by `rpmbuild` proceed with that source file instead so an `if aix53; then do odd stuff; else`

2020-10-20 14:05 UTC, vpodzime reviewed
Looks good to me. Let's make sure it builds everywhere! :crossed_fingers:

2020-10-20 14:10 UTC, craigcomstock commented
Started a job for exotics: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=5819)](https://ci.cfengine.com/job/pr-pipeline/5819/)

and for NON exotics: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=5820)](https://ci.cfengine.com/job/pr-pipeline/5820/)

2020-10-20 20:13 UTC, craigcomstock commented
@cf-bottom jenkins with exotics

2020-10-20 20:13 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5827)](https://ci.cfengine.com//job/pr-pipeline/5827/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5827/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5827/

2020-10-21 15:38 UTC, cf-bottom requested changes
Please use a company e-mail instead of c***@unreasonablefarm.org

2020-10-22 13:08 UTC, vpodzime reviewed
Looks good to me. Please squash the commits (with the correct email address).

2020-10-22 16:44 UTC, craigcomstock commented
hpux is green! :) [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=testing-pr%2Flabel%3DPACKAGES_ia64_hpux_11.23&build=11450)](https://ci.cfengine.com/job/testing-pr/label=PACKAGES_ia64_hpux_11.23/11450/)

2020-10-22 17:17 UTC, craigcomstock commented
solaris 11 is also green! [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=testing-pr%2Flabel%3DPACKAGES_sparc64_solaris_11&build=11453)](https://ci.cfengine.com/job/testing-pr/label=PACKAGES_sparc64_solaris_11/11453/)

So no, @cf-bottom please do a final round on jenkins with exotics, see how it goes. :) I have squashed commits and fixed the signing email (several commits ago actually) so should be :green_light: after an all green jenkins run.

2020-10-22 17:18 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5849)](https://ci.cfengine.com//job/pr-pipeline/5849/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5849/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5849/

2020-10-22 19:39 UTC, vpodzime approved these changes
Looks good to me. Good job, @craigcomstock :clap:

2020-10-22 19:39 UTC, vpodzime commented on deps-packaging/diffutils/mingw/debian/control
> + CFEngine Build Automation -- diffutils -- mingw64
Is this duplicated on purpose or just a copy-pasta error?

2020-10-22 20:16 UTC, craigcomstock commented on deps-packaging/diffutils/mingw/debian/control
> + CFEngine Build Automation -- diffutils -- mingw64
Duplicated on most deps so cargo cult copy-pasta recipe. If changed it would tweak lots of debian packages. It won't really matter in the end I think since these are just for the cfbuild-<dep>.deb files that get unpacked and consolidated into cfengine-*.deb.

I tried locally building diffutils deb without the duplication and had no problem running dpkg-deb -I on the result.

I think it is a bit of a pattern for the first line to be a summary: `Description: <summary>` and then subsequent lines indented with a longer description. From looking at a few .deb files I had laying around.

2020-10-23 08:50 UTC, vpodzime commented
Merging so that I can test https://github.com/cfengine/core/pull/4353 properly.

2020-10-23 08:50 UTC, merged