ENT-6101 drop unsupported platforms
cfengine/buildscripts pull request #840
Opened 2021-06-11 14:14 UTC by Lex-2008

And add Ubuntu 20

2021-06-12 12:18 UTC, cf-bottom commented
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

2021-07-02 14:05 UTC, craigcomstock approved these changes

2021-07-05 09:29 UTC, vpodzime requested changes
The first commit message of the first commit is wrong. It should use `<` instead of `<=` and also, the commit leaves Ubuntu 16 in the list(s) so clearly `Ubuntu < 16` is unsupported.

2021-07-05 09:29 UTC, vpodzime commented on build-scripts/package
> +    TARBALL="$BASEDIR/$PKG/pkg/$PKG-$DEB_VERSION$safe_prefix.$os_version_major.$ARCH.pkg.tar.gz"
Shouldn't `$os_version_major` be dropped as well?

2021-07-05 12:29 UTC, vpodzime approved these changes
Looks good to me now.

2021-07-05 12:43 UTC, merged