ENT-7554: Changed 4th octet in Windows package version to match package release number
cfengine/buildscripts pull request #858
Opened 2021-08-25 21:02 UTC by nickanderson

With this change the 4th octet in the version of the package meta data and
ultimately stored in the registry should match the release number in the package
filename.

Ticket: ENT-7554
Changelog: Title

2021-08-30 15:43 UTC, Lex-2008 requested changes

2021-08-30 15:43 UTC, Lex-2008 commented on build-scripts/package-msi
> +        REVISION="1"
I think it should be `REVISION="$EXPLICIT_VERSION.1"`, not just "1". Otherwise, all our MSI packages will have version 1.0.0.0 :)

2021-08-31 14:15 UTC, nickanderson commented on build-scripts/package-msi
> +        REVISION="1"
OK, same thing for the else  then ...

2021-08-31 14:15 UTC, nickanderson commented on build-scripts/package-msi
> +        REVISION="1"
Updated, please re-review

2021-08-31 14:16 UTC, Lex-2008 approved these changes

2021-10-11 18:48 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=7165)](https://ci.cfengine.com//job/pr-pipeline/7165/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7165/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7165/

2021-10-20 18:57 UTC, merged